spring:
    liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.xml
    jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: validate
    datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driverClassName: org.postgresql.Driver

    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

server:
  port: 8081