spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      schema-locations: classpath*:init_table.sql

server:
  port: 8081